### PR TITLE
Fixed two errors in lectureC02

### PR DESCRIPTION
**Pull request by anhsmith**

### CODE REVIEW

**Comment by jmarshallnz** [comment]
Nice! Do you want to try a rebase again? (I've tested and it works fine)

Steps:
1. Fetch down my main (dunno what you have it called - see `git remote`) `git fetch jmarshallnz main`
2. If necessary, switch to this branch. `git checkout working-as`
3. Rebase it on my main: `git rebase jmarshallnz/main`

You should then end up with a single commit (Fixed 2 errors in lectureC02) and the merge commit will be gone. Then, `git push -f origin working-as` to push back up to github.

**Comment by anhsmith** [comment]
I think that might've worked...?

**Comment by jmarshallnz** [comment]
Perfect - nice job!

(Re the horses commit - In another version of the same dataset I have an additional observation that is very tall for a donkey...)

Will pull in now if you're happy with things.

**Comment by anhsmith** [comment]
I'm happy with things!

I re-recorded the middle part of that lecture, where the audio had failed.
The lecture is now up in three parts, which isn't ideal, but it works.

I'll do the workshop recordings now.

Adam

**Comment by jmarshallnz** [comment]
Great. Merged. Procedure now for you would be to fetch my main branch again then rebase your main on mine. Then either keep your working-as branch and rebase that again onto my main, or start a new one for additional changes.

**Pull request merged**
